allowBuilds:
  '@reown/appkit': false
  '@swc/core': false
  bigint-buffer: false
  bufferutil: false
  esbuild: false
  keccak: false
  protobufjs: false
  utf-8-validate: false
minimumReleaseAgeExclude:
  - ox@0.14.45
  - viem@2.56.7
